---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

# Comment out resources to not render servicemesh
# resources:
#   - namespace.yaml
#   - servicemesh-controlplane.yaml
