---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-limits.yaml
    target:
      group: autoscaling.openshift.io
      kind: ClusterAutoscaler
      name: default
