apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

# Commenting out the below in order to let the LZTVP own the gitops-operator
# resources:
#   - openshift-gitops.yaml
