apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: iris
    serving.knative.openshift.io/enablePassthrough: 'true'
    serving.kserve.io/deploymentMode: Serverless
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: iris
  namespace: fharo-testing
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: onnx
        version: '1'
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      runtime: iris
      storage:
        key: iris-data-connection
        path: iris-pipeline/d4ef5920-fce5-4a76-acbe-126199275f77/model-to-onnx/445ef038-76d6-4788-9b1d-630a7da762eb/onnx_model_file
status:
  address:
    url: 'https://iris.fharo-testing-2.svc.cluster.local'
  components:
    predictor:
      address:
        url: 'http://iris-predictor.fharo-testing-2.svc.cluster.local'
      latestCreatedRevision: iris-predictor-00001
      latestReadyRevision: iris-predictor-00001
      latestRolledoutRevision: iris-predictor-00001
      traffic:
        - latestRevision: true
          percent: 100
          revisionName: iris-predictor-00001
      url: 'https://iris-predictor-fharo-testing-2.voicd-us-east-3-4cb626ac15bdff235c2f3fba02223e28-0000.us-east.containers.appdomain.cloud'
  conditions:
    - lastTransitionTime: '2025-07-01T21:28:22Z'
      status: 'True'
      type: IngressReady
    - lastTransitionTime: '2025-07-01T21:24:21Z'
      severity: Info
      status: 'True'
      type: LatestDeploymentReady
    - lastTransitionTime: '2025-07-01T21:24:21Z'
      severity: Info
      status: 'True'
      type: PredictorConfigurationReady
    - lastTransitionTime: '2025-07-01T21:28:22Z'
      status: 'True'
      type: PredictorReady
    - lastTransitionTime: '2025-07-01T21:28:22Z'
      severity: Info
      status: 'True'
      type: PredictorRouteReady
    - lastTransitionTime: '2025-07-01T21:28:22Z'
      status: 'True'
      type: Ready
    - lastTransitionTime: '2025-07-01T21:28:22Z'
      severity: Info
      status: 'True'
      type: RoutesReady
  deploymentMode: Serverless
  modelStatus:
    copies:
      failedCopies: 0
      totalCopies: 1
    states:
      activeModelState: Loaded
      targetModelState: Loaded
    transitionStatus: UpToDate
  observedGeneration: 1
  url: 'https://iris-fharo-testing-2.voicd-us-east-3-4cb626ac15bdff235c2f3fba02223e28-0000.us-east.containers.appdomain.cloud'
