apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../../instance/overlays/default
  - ../../../operator/overlays/stable

configMapGenerator:
  - name: nvidia-dcgm-exporter-dashboard
    namespace: openshift-config-managed
    behavior: replace
    files:
      - https://github.com/NVIDIA/dcgm-exporter/raw/main/grafana/dcgm-exporter-dashboard.json

patches:
  - target:
      kind: OperatorGroup
      name: gpu-operator-certified 
    patch: |-
      - op: replace
        path: "/metadata/name"
        value: nvidia-gpu-operator-group

  - target:
      kind: Subscription
      name: gpu-operator-certified
      namespace: nvidia-gpu-operator
    patch: |-
      - op: replace
        path: "/spec/installPlanApproval"
        value: Manual
  
