- op: add
  path: /spec/template/spec/ignoreDifferences/-
  value:
    kind: Namespace
    group: ""
    name: redhat-ods-operator
    jqPathExpressions:
      - .
- op: add
  path: /spec/template/spec/ignoreDifferences/-
  value:
    kind: ClusterRole
    group: rbac.authorization.k8s.io
    name: admingroupcluster-role
    jqPathExpressions:
      - .metadata.ownerReferences
      - .metadata.labels
      - .metadata.annotations
      - .rules
- op: add
  path: /spec/template/spec/ignoreDifferences/-
  value:
    kind: ConsolePlugin
    group: console.openshift.io
    name: pipelines-console-plugin
    jqPathExpressions:
      - .
