apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configs
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: console-notifications
          path: components/cluster-configs/console-notifications/overlays/rhoai-ibmcloud-lab
      # - cluster: local
      #   url: https://kubernetes.default.svc
      #   values:
      #     name: cluster-autoscaling
      #     path: components/cluster-configs/autoscaling/overlays/default
