kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: standard-workbench
  namespace: fharo-testing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeMode: Filesystem