apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Frankie's resources for testing.
  - fharo-testing-pvc.yaml
  - fharo-testing-notebook-workbench.yaml
  - fharo-testing-minio-data-connection.yaml